
export const FA_ICONS = [
  'fa-address-book', 'fa-address-card', 'fa-adjust', 'fa-align-center',
  'fa-align-justify', 'fa-align-left', 'fa-align-right', 'fa-allergies',
  'fa-ambulance', 'fa-anchor', 'fa-angle-double-down', 'fa-angle-double-left',
  'fa-angle-double-right', 'fa-angle-double-up', 'fa-angle-down', 'fa-angle-left',
  'fa-angle-right', 'fa-angle-up', 'fa-archive', 'fa-arrow-alt-circle-down',
  'fa-arrow-alt-circle-left', 'fa-arrow-alt-circle-right', 'fa-arrow-alt-circle-up',
  'fa-arrow-circle-down', 'fa-arrow-circle-left', 'fa-arrow-circle-right', 'fa-arrow-circle-up',
  'fa-arrow-down', 'fa-arrow-left', 'fa-arrow-right', 'fa-arrow-up', 'fa-arrows-alt',
  'fa-arrows-alt-h', 'fa-arrows-alt-v', 'fa-assistive-listening-systems', 'fa-asterisk',
  'fa-at', 'fa-atlas', 'fa-atom', 'fa-audio-description', 'fa-award', 'fa-backward',
  'fa-balance-scale', 'fa-ban', 'fa-band-aid', 'fa-barcode', 'fa-bars', 'fa-baseball-ball',
  'fa-basketball-ball', 'fa-bath', 'fa-battery-empty', 'fa-battery-full', 'fa-battery-half',
  'fa-battery-quarter', 'fa-battery-three-quarters', 'fa-bed', 'fa-beer', 'fa-bell',
  'fa-bell-slash', 'fa-bicycle', 'fa-binoculars', 'fa-birthday-cake', 'fa-blender',
  'fa-blind', 'fa-bold', 'fa-bolt', 'fa-bomb', 'fa-bone', 'fa-book', 'fa-book-open',
  'fa-book-reader', 'fa-bookmark', 'fa-bowling-ball', 'fa-box', 'fa-box-open', 'fa-boxes',
  'fa-braille', 'fa-brain', 'fa-briefcase', 'fa-briefcase-medical', 'fa-broadcast-tower',
  'fa-broom', 'fa-brush', 'fa-bug', 'fa-building', 'fa-bullhorn', 'fa-bullseye', 'fa-burn',
  'fa-bus', 'fa-calculator', 'fa-calendar', 'fa-calendar-alt', 'fa-calendar-check',
  'fa-calendar-minus', 'fa-calendar-plus', 'fa-calendar-times', 'fa-camera', 'fa-camera-retro',
  'fa-capsules', 'fa-car', 'fa-caret-down', 'fa-caret-left', 'fa-caret-right', 'fa-caret-square-down',
  'fa-caret-square-left', 'fa-caret-square-right', 'fa-caret-square-up', 'fa-caret-up',
  'fa-cart-arrow-down', 'fa-cart-plus', 'fa-certificate', 'fa-chair', 'fa-chalkboard',
  'fa-chalkboard-teacher', 'fa-chart-area', 'fa-chart-bar', 'fa-chart-line', 'fa-chart-pie',
  'fa-check', 'fa-check-circle', 'fa-check-double', 'fa-check-square', 'fa-chess',
  'fa-chevron-circle-down', 'fa-chevron-circle-left', 'fa-chevron-circle-right', 'fa-chevron-circle-up',
  'fa-chevron-down', 'fa-chevron-left', 'fa-chevron-right', 'fa-chevron-up', 'fa-child',
  'fa-church', 'fa-circle', 'fa-circle-notch', 'fa-city', 'fa-clipboard', 'fa-clipboard-check',
  'fa-clipboard-list', 'fa-clock', 'fa-clone', 'fa-closed-captioning', 'fa-cloud', 'fa-cloud-download-alt',
  'fa-cloud-upload-alt', 'fa-cocktail', 'fa-code', 'fa-code-branch', 'fa-coffee', 'fa-cog',
  'fa-cogs', 'fa-coins', 'fa-columns', 'fa-comment', 'fa-comment-alt', 'fa-comment-dots',
  'fa-comment-slash', 'fa-comments', 'fa-compact-disc', 'fa-compass', 'fa-compress', 'fa-concierge-bell',
  'fa-cookie', 'fa-cookie-bite', 'fa-copy', 'fa-copyright', 'fa-couch', 'fa-credit-card',
  'fa-crop', 'fa-crop-alt', 'fa-crosshairs', 'fa-crow', 'fa-crown', 'fa-cube', 'fa-cubes',
  'fa-cut', 'fa-database', 'fa-deaf', 'fa-desktop', 'fa-diagnoses', 'fa-dice', 'fa-dice-d20',
  'fa-digital-tachograph', 'fa-directions', 'fa-divide', 'fa-dizzy', 'fa-dna', 'fa-dollar-sign',
  'fa-dolly', 'fa-dolly-flatbed', 'fa-donate', 'fa-door-closed', 'fa-door-open', 'fa-dot-circle',
  'fa-dove', 'fa-download', 'fa-drafting-compass', 'fa-dragon', 'fa-draw-polygon', 'fa-drum',
  'fa-drum-steelpan', 'fa-dumbbell', 'fa-edit', 'fa-eject', 'fa-ellipsis-h', 'fa-ellipsis-v',
  'fa-envelope', 'fa-envelope-open', 'fa-envelope-square', 'fa-equals', 'fa-eraser', 'fa-euro-sign',
  'fa-exchange-alt', 'fa-exclamation', 'fa-exclamation-circle', 'fa-exclamation-triangle',
  'fa-expand', 'fa-expand-arrows-alt', 'fa-external-link-alt', 'fa-external-link-square-alt',
  'fa-eye', 'fa-eye-dropper', 'fa-eye-slash', 'fa-fast-backward', 'fa-fast-forward', 'fa-fax',
  'fa-feather', 'fa-feather-alt', 'fa-female', 'fa-fighter-jet', 'fa-file', 'fa-file-alt',
  'fa-file-archive', 'fa-file-audio', 'fa-file-code', 'fa-file-contract', 'fa-file-csv',
  'fa-file-download', 'fa-file-excel', 'fa-file-export', 'fa-file-image', 'fa-file-import',
  'fa-file-invoice', 'fa-file-invoice-dollar', 'fa-file-medical', 'fa-file-medical-alt',
  'fa-file-pdf', 'fa-file-powerpoint', 'fa-file-prescription', 'fa-file-signature', 'fa-file-upload',
  'fa-file-video', 'fa-file-word', 'fa-fill', 'fa-fill-drip', 'fa-film', 'fa-filter', 'fa-fingerprint',
  'fa-fire', 'fa-fire-extinguisher', 'fa-first-aid', 'fa-fish', 'fa-flag', 'fa-flag-checkered',
  'fa-flask', 'fa-flushed', 'fa-folder', 'fa-folder-minus', 'fa-folder-open', 'fa-folder-plus',
  'fa-font', 'fa-football-ball', 'fa-forward', 'fa-frog', 'fa-frown', 'fa-frown-open',
  'fa-futbol', 'fa-gamepad', 'fa-gas-pump', 'fa-gavel', 'fa-gem', 'fa-genderless', 'fa-gift',
  'fa-glass-martini', 'fa-glass-martini-alt', 'fa-glasses', 'fa-globe', 'fa-globe-africa',
  'fa-globe-americas', 'fa-globe-asia', 'fa-golf-ball', 'fa-graduation-cap', 'fa-greater-than',
  'fa-greater-than-equal', 'fa-grimace', 'fa-grin', 'fa-grin-alt', 'fa-grin-beam',
  'fa-grin-beam-sweat', 'fa-grin-hearts', 'fa-grin-squint', 'fa-grin-squint-tears',
  'fa-grin-stars', 'fa-grin-tears', 'fa-grin-tongue', 'fa-grin-tongue-squint',
  'fa-grin-tongue-wink', 'fa-grin-wink', 'fa-grip-horizontal', 'fa-grip-vertical',
  'fa-h-square', 'fa-hand-holding', 'fa-hand-holding-heart', 'fa-hand-holding-usd',
  'fa-hand-lizard', 'fa-hand-paper', 'fa-hand-peace', 'fa-hand-point-down',
  'fa-hand-point-left', 'fa-hand-point-right', 'fa-hand-point-up', 'fa-hand-pointer',
  'fa-hand-rock', 'fa-hand-scissors', 'fa-hand-spock', 'fa-hands', 'fa-hands-helping',
  'fa-handshake', 'fa-hashtag', 'fa-hdd', 'fa-heading', 'fa-headphones', 'fa-headphones-alt',
  'fa-headset', 'fa-heart', 'fa-heartbeat', 'fa-helicopter', 'fa-highlighter', 'fa-history',
  'fa-hockey-puck', 'fa-home', 'fa-hospital', 'fa-hospital-alt', 'fa-hospital-symbol',
  'fa-hot-tub', 'fa-hotel', 'fa-hourglass', 'fa-hourglass-end', 'fa-hourglass-half',
  'fa-hourglass-start', 'fa-i-cursor', 'fa-id-badge', 'fa-id-card', 'fa-id-card-alt',
  'fa-image', 'fa-images', 'fa-inbox', 'fa-indent', 'fa-industry', 'fa-infinity',
  'fa-info', 'fa-info-circle', 'fa-italic', 'fa-key', 'fa-keyboard', 'fa-kiss', 'fa-kiss-beam',
  'fa-kiss-wink-heart', 'fa-kiwi-bird', 'fa-language', 'fa-laptop', 'fa-laptop-code',
  'fa-laugh', 'fa-laugh-beam', 'fa-laugh-squint', 'fa-laugh-wink', 'fa-layer-group',
  'fa-leaf', 'fa-lemon', 'fa-less-than', 'fa-less-than-equal', 'fa-level-down-alt',
  'fa-level-up-alt', 'fa-life-ring', 'fa-lightbulb', 'fa-link', 'fa-lira-sign',
  'fa-list', 'fa-list-alt', 'fa-list-ol', 'fa-list-ul', 'fa-location-arrow',
  'fa-lock', 'fa-lock-open', 'fa-long-arrow-alt-down', 'fa-long-arrow-alt-left',
  'fa-long-arrow-alt-right', 'fa-long-arrow-alt-up', 'fa-low-vision', 'fa-magic',
  'fa-magnet', 'fa-male', 'fa-map', 'fa-map-marked', 'fa-map-marked-alt', 'fa-map-marker',
  'fa-map-marker-alt', 'fa-map-pin', 'fa-map-signs', 'fa-marker', 'fa-mars', 'fa-mars-double',
  'fa-mars-stroke', 'fa-mars-stroke-h', 'fa-mars-stroke-v', 'fa-medal', 'fa-medkit',
  'fa-meh', 'fa-meh-blank', 'fa-meh-rolling-eyes', 'fa-memory', 'fa-mercury', 'fa-microchip',
  'fa-microphone', 'fa-microphone-alt', 'fa-microphone-alt-slash', 'fa-microphone-slash',
  'fa-microscope', 'fa-minus', 'fa-minus-circle', 'fa-minus-square', 'fa-mobile', 'fa-mobile-alt',
  'fa-money-bill', 'fa-money-bill-alt', 'fa-money-bill-wave', 'fa-money-bill-wave-alt',
  'fa-money-check', 'fa-money-check-alt', 'fa-monument', 'fa-moon', 'fa-mortar-pestle',
  'fa-motorcycle', 'fa-mouse-pointer', 'fa-music', 'fa-neuter', 'fa-newspaper', 'fa-not-equal',
  'fa-notes-medical', 'fa-object-group', 'fa-object-ungroup', 'fa-outdent', 'fa-paint-brush',
  'fa-paint-roller', 'fa-palette', 'fa-pallet', 'fa-paper-plane', 'fa-paperclip', 'fa-parachute-box',
  'fa-paragraph', 'fa-parking', 'fa-passport', 'fa-paste', 'fa-pause', 'fa-pause-circle',
  'fa-paw', 'fa-pen', 'fa-pen-alt', 'fa-pen-fancy', 'fa-pen-nib', 'fa-pen-square',
  'fa-pencil-alt', 'fa-pencil-ruler', 'fa-people-carry', 'fa-percent', 'fa-percentage',
  'fa-phone', 'fa-phone-slash', 'fa-phone-square', 'fa-phone-volume', 'fa-piggy-bank',
  'fa-pills', 'fa-plane', 'fa-plane-arrival', 'fa-plane-departure', 'fa-play', 'fa-play-circle',
  'fa-plug', 'fa-plus', 'fa-plus-circle', 'fa-plus-square', 'fa-podcast', 'fa-poo', 'fa-poop',
  'fa-portrait', 'fa-pound-sign', 'fa-power-off', 'fa-prescription', 'fa-prescription-bottle',
  'fa-prescription-bottle-alt', 'fa-print', 'fa-procedures', 'fa-project-diagram', 'fa-puzzle-piece',
  'fa-qrcode', 'fa-question', 'fa-question-circle', 'fa-quidditch', 'fa-quote-left',
  'fa-quote-right', 'fa-random', 'fa-receipt', 'fa-recycle', 'fa-redo', 'fa-redo-alt',
  'fa-registered', 'fa-reply', 'fa-reply-all', 'fa-retweet', 'fa-ribbon', 'fa-road', 'fa-robot',
  'fa-rocket', 'fa-route', 'fa-rss', 'fa-rss-square', 'fa-ruble-sign', 'fa-ruler',
  'fa-ruler-combined', 'fa-ruler-horizontal', 'fa-ruler-vertical', 'fa-running', 'fa-rupee-sign',
  'fa-sad-cry', 'fa-sad-tear', 'fa-save', 'fa-school', 'fa-screwdriver', 'fa-search',
  'fa-search-dollar', 'fa-search-location', 'fa-search-minus', 'fa-search-plus', 'fa-seedling',
  'fa-server', 'fa-share', 'fa-share-alt', 'fa-share-alt-square', 'fa-share-square',
  'fa-shekel-sign', 'fa-shield-alt', 'fa-ship', 'fa-shipping-fast', 'fa-shoe-prints',
  'fa-shopping-bag', 'fa-shopping-basket', 'fa-shopping-cart', 'fa-shower', 'fa-shuttle-van',
  'fa-sign', 'fa-sign-in-alt', 'fa-sign-language', 'fa-sign-out-alt', 'fa-signal', 'fa-signature',
  'fa-sitemap', 'fa-skull', 'fa-sliders-h', 'fa-smile', 'fa-smile-beam', 'fa-smile-wink',
  'fa-smoking', 'fa-smoking-ban', 'fa-snowflake', 'fa-solar-panel', 'fa-sort',
  'fa-sort-alpha-down', 'fa-sort-alpha-up', 'fa-sort-amount-down', 'fa-sort-amount-up',
  'fa-sort-down', 'fa-sort-numeric-down', 'fa-sort-numeric-up', 'fa-sort-up', 'fa-spa',
  'fa-space-shuttle', 'fa-spinner', 'fa-splotch', 'fa-spray-can', 'fa-square', 'fa-square-full',
  'fa-stamp', 'fa-star', 'fa-star-half', 'fa-star-half-alt', 'fa-step-backward',
  'fa-step-forward', 'fa-stethoscope', 'fa-sticky-note', 'fa-stop', 'fa-stop-circle',
  'fa-stopwatch', 'fa-store', 'fa-store-alt', 'fa-stream', 'fa-street-view', 'fa-strikethrough',
  'fa-stroopwafel', 'fa-subscript', 'fa-subway', 'fa-suitcase', 'fa-suitcase-rolling',
  'fa-sun', 'fa-superscript', 'fa-surprise', 'fa-swatchbook', 'fa-swimmer', 'fa-sync',
  'fa-sync-alt', 'fa-syringe', 'fa-table', 'fa-table-tennis', 'fa-tablet', 'fa-tablet-alt',
  'fa-tablets', 'fa-tachometer-alt', 'fa-tag', 'fa-tags', 'fa-tape', 'fa-tasks', 'fa-taxi',
  'fa-teeth', 'fa-teeth-open', 'fa-terminal', 'fa-text-height', 'fa-text-width', 'fa-th',
  'fa-th-large', 'fa-th-list', 'fa-thermometer', 'fa-thermometer-empty', 'fa-thermometer-full',
  'fa-thermometer-half', 'fa-thermometer-quarter', 'fa-thermometer-three-quarters',
  'fa-thumbs-down', 'fa-thumbs-up', 'fa-thumbtack', 'fa-ticket-alt', 'fa-times', 'fa-times-circle',
  'fa-tint', 'fa-tint-slash', 'fa-tired', 'fa-toggle-off', 'fa-toggle-on', 'fa-toolbox',
  'fa-tooth', 'fa-trademark', 'fa-traffic-light', 'fa-train', 'fa-transgender', 'fa-transgender-alt',
  'fa-trash', 'fa-trash-alt', 'fa-tree', 'fa-trophy', 'fa-truck', 'fa-truck-loading',
  'fa-truck-monster', 'fa-truck-moving', 'fa-truck-pickup', 'fa-tshirt', 'fa-tty', 'fa-tv',
  'fa-umbrella', 'fa-umbrella-beach', 'fa-underline', 'fa-undo', 'fa-undo-alt', 'fa-universal-access',
  'fa-university', 'fa-unlink', 'fa-unlock', 'fa-unlock-alt', 'fa-upload', 'fa-user', 'fa-user-alt',
  'fa-user-alt-slash', 'fa-user-astronaut', 'fa-user-check', 'fa-user-circle', 'fa-user-clock',
  'fa-user-cog', 'fa-user-edit', 'fa-user-friends', 'fa-user-graduate', 'fa-user-injured',
  'fa-user-lock', 'fa-user-md', 'fa-user-minus', 'fa-user-ninja', 'fa-user-plus',
  'fa-user-secret', 'fa-user-shield', 'fa-user-slash', 'fa-user-tag', 'fa-user-tie',
  'fa-user-times', 'fa-users', 'fa-users-cog', 'fa-utensil-spoon', 'fa-utensils',
  'fa-vector-square', 'fa-venus', 'fa-venus-double', 'fa-venus-mars', 'fa-vial', 'fa-vials',
  'fa-video', 'fa-video-slash', 'fa-volleyball-ball', 'fa-volume-down', 'fa-volume-off',
  'fa-volume-up', 'fa-walking', 'fa-wallet', 'fa-warehouse', 'fa-weight', 'fa-weight-hanging',
  'fa-wheelchair', 'fa-wifi', 'fa-window-close', 'fa-window-maximize', 'fa-window-minimize',
  'fa-window-restore', 'fa-wine-glass', 'fa-wine-glass-alt', 'fa-won-sign', 'fa-wrench',
  'fa-x-ray', 'fa-yen-sign'
]
